
means_of_transport:
  types:
    0: "walking"
    1: "bike"
    2: "scooter"
    3: "bus"
  car:
    co2_emission:
      "0": 100 #for gasoline avg co2 emission gCo2/km
      "1": 120  #for diesel gCo2/km
    default_avg_consumption: 10 #l/100km
    default_avg_fuel_price:
      "0": 6.52 #for gasoline
      "1": 6.70 #for diesel
  scooter:
    start_price: 2.5 #All the data takes from blinkee
    cost_for_minute: 0.69
    avg_speed: 10 #km/h
    avg_consumption: 0.1 #kWh/100km
    avg_co2_emission: 4 #gCO2/kWh

  bike:
    price_per_hour: 1 #zł
    avg_speed: 10 #km/h

  params:
    transport_type:
      value: "transport_type"
      default: 2 #bus
    distance:
      value: "distance"
      default: 10
    avg_consumption:
      value: "avg_consumption"
      default: null
    fuel_type:
      value: "fuel_type"
      default: 0 #gasoline
    fuel_price:
      value: "fuel_price"
      default: null
    daily_distance:
      value: "daily_distance"
      default: 25 #avg daily trip for rzeszowian
    lon:
      value: "lon"
      default: null
    lat:
      value: "lat"
      default: null


paid_parking:
  data: "paid_parking_zones/data"
  input_coordinates_format: "EPSG:4326"
  output_coordinates_format: "EPSG:2180"
  parking_price: #based on official pricing for 2023 - we asssume parking for one hour
      I: 5
      II: 3
      III: 3
      IV: 3

air_pollution:
  default_sensor_id: 10125 #sensor on piłsudskiego street  in Rzeszów, if missing user location we use default
  sensor_list_data: "air_quality/data/sensors.json"
  air_pollution_url: "https://api.gios.gov.pl/pjp-api/rest/aqindex/getIndex/"
  air_index_key: "stIndexLevel"
  index_level: "indexLevelName"
  extra_points: #rules for extra points based on air quality
    0: 0
    1: 0
    2: 50
    3: 100
    4: 150
    5: 200
  params:
    lat: "lat"
    lon: "lon"



traffic:
  average_traffic_file: 'traffic_intensity/data/global_avarage_traffic.csv'
  hour: "Hour"
  day_of_week: "Week_day"
  params:
    hour: "hour"
    day_of_week: "day_of_week"
  traffic_result: "traffic"
